### ISSUE TITLE
Location of R directory

### ISSUE THREAD

**Issue by karanpreetkaur** [UBC-MDS/r_outliers_utils#3]
Hi @scarlqq 

I don't see R directory in our github project structure. Could you please let me know how you have made changes ?

**Comment by scarlqq** [comment]
`use_r("functionname")`
run this line in our `routliersutils.Rproj` after `library(devtools)`, it will generate the `R` directory and the r file for you.

**Comment by karanpreetkaur** [comment]
ok thanks @scarlqq
